version: "3.4"
services:
  worker-service:
    container_name: worker-service
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./:/graham
    working_dir: /graham
    command: "dotnet run"
    ports:
      - "8001:8081"