name: Docker Worker Service Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build app
        run: |
          docker build ./DockerExampleWorkerService -t graham28ppb/example1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./DockerExampleWorkerService
        run: docker-compose up